In [2]:
#Experiment2
#Amirhesam_Nakhaee
#Hassan_Farhoud

import numpy as np

def sig(x) :
    y = (2/(1+np.exp(-x))-1)
    return y
def sigdot (x) : 
    y = (1 -  sig(x) ** 2)/2
    return y

class perceptron :
    def __init__(self ,n ) :
        self.w = np.random.random((n,1))*0.01
        

    def forward(self ,x):
        self.x = x
        y = sig(x @ self.w)
        return y

    def grad(self ,label,x,k):
        y_pre = self.forward(x)
        err = label - y_pre
        grad = (np.transpose((sigdot(x) * x))) @ err
        i = 0
        while np.mean(err)  > 0.001 :
            i += 1
            # print(f'mean(err) = {np.mean(err)}')
            self.w += grad*k
            y_pre = self.forward(x)
            err = label - y_pre
        print(f'mean(err) = {np.mean(err)}')
        # print(i)
        j = 0
        for i in y_pre :
            if i > 0.5 :
                y_pre[j] = 1
            else :
                y_pre[j] = 0
            j += 1
        return y_pre
            
ins = perceptron(2)
x = np.array([[0,0],[0,1],[1,0],[1,1]])
label = np.array([[0],[0],[0],[1]])

print(f'\n result : \n{ins.grad(label ,x ,0.1)}')


mean(err) = -0.00967959317527367

 result : 
[[0.]
 [0.]
 [0.]
 [1.]]


In [3]:
#HW1

import numpy as np

def sig(x) :
    y = (2/(1 + np.exp(-x))) - 1
    return y
def sigdot (x) : 
    y = (1 -  sig(x) ** 2)/2
    return y

class perceptron :
    def __init__(self ,n ) :
        self.w = np.random.random((n+1,1)) + 1
        

    def forward(self ,x):
        bios = np.ones(np.shape(x)[0])
        self.x = np.c_[x,bios]
        y = sig(self.x @ self.w)
        return y

    def grad(self ,label,x,k):
        y_pre = self.forward(x)
        err = y_pre - label
        grad = (np.transpose((sigdot(self.x) * self.x))) @ -err
        i = 0
        while np.mean(err)  > 0.005 :
            # print(f'sum(err) = {sum(err)}')
            i += 1
            self.w += grad*k
            y_pre = self.forward(x)
            err = y_pre - label
        print(f'mean(err) = {np.mean(err)}')
        print(i)
        j = 0
        for i in y_pre :
            if i > 0.5 :
                y_pre[j] = 1
            else :
                y_pre[j] = 0
            j += 1
        return y_pre
            
ins = perceptron(2)
x = np.array([[0,0],[0,1],[1,0],[1,1]])
label = np.array([[0],[0],[0],[1]])

print(f'\n result : \n{ins.grad(label ,x ,0.01)}')


mean(err) = 0.002237306530760874
198

 result : 
[[0.]
 [0.]
 [0.]
 [1.]]


In [4]:
#HW4

import numpy as np

def sig(x) :
    y = (2/(1+np.exp(-x))-1)
    return y
def sigdot (x) : 
    y = (1 -  sig(x) ** 2)/2
    return y

class perceptron :
    def __init__(self ,n ) :
        self.w = np.random.random((n,1))*0.01
        

    def forward(self ,x):
        self.x = x
        y = sig(x @ self.w)
        return y

    def grad(self ,label,x,k):
        y_pre = self.forward(x)
        err = label - y_pre
        grad = (np.transpose((sigdot(x) * x))) @ err
        i = 0
        while np.mean(err)  > 0.00001 :
            i += 1
            # print(f'mean(err) = {np.mean(err)}')
            self.w += grad*k
            y_pre = self.forward(x)
            err = label - y_pre
        print(f'mean(err) = {np.mean(err)}')
        print(i)
        j = 0
        for i in y_pre :
            if i > 0.5 :
                y_pre[j] = 1
            else :
                y_pre[j] = 0
            j += 1
        return y_pre
            
x = np.array([[0,0],[0,1],[1,0],[1,1]])

ins_or = perceptron(2)
label_or = np.array([[0],[1],[1],[1]])
print(f'\n result : \n{ins_or.grad(label_or ,x ,0.1)}')

ins_and = perceptron(2)
label_and = np.array([[0],[0],[0],[1]])
print(f'\n result : \n{ins_and.grad(label_and ,x ,0.1)}')



ins_xor = perceptron(2)
label_xor= np.array([[0],[1],[1],[0]])
print(f'\n result : \n{ins_xor.grad(label_xor ,x ,0.1)}')


mean(err) = 9.317954521859129e-06
148

 result : 
[[0.]
 [1.]
 [1.]
 [1.]]
mean(err) = -0.00999891785168222
14

 result : 
[[0.]
 [0.]
 [0.]
 [1.]]
mean(err) = -0.008862721851679856
34

 result : 
[[0.]
 [1.]
 [1.]
 [1.]]


In [9]:
#HW5
from ucimlrepo import fetch_ucirepo 
import numpy as np
import sys
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
# print(iris.metadata) 
  
# # variable information 
# print(iris.variables) 


def sig(x) :
    y = (2/(1+np.exp(-x))-1)
    return y
def sigdot (x) : 
    y = (1 -  sig(x) ** 2)/2
    return y

class perceptron :
    def __init__(self ,n ) :
        self.w = np.random.random((n,1))*0.01
        

    def forward(self ,x):
        self.x = x
        y = sig(x @ self.w)
        return y

    def grad(self ,label,x,k):
        y_pre = self.forward(x)
        err = label - y_pre
        grad = (np.transpose((sigdot(x) * x))) @ err
        i = 0
        # print(err)
        while np.mean(err)  > 0.005 :
            i += 1
            # print(f'mean(err) = {np.mean(err)}')
            self.w += grad*k
            y_pre = self.forward(x)
            err = label - y_pre
        print(f'mean(err) = {np.mean(err)}')
        print(i)
        j = 0
        for i in y_pre :
            if i > 0.6 :
                y_pre[j] = 1
            else :
                y_pre[j] = 0
            j += 1
        return y_pre


inss = perceptron(4)
x= []
for i in range(150) :
    for j in range(4):
        x.append(X.iloc[i][j])
x = np.array(x)
x = x.reshape(150,4)
# print(x)
Y = []
for i in range(150) :
    if y.iloc[i][0] == 'Iris-setosa' :
        Y.append(0)
    elif y.iloc[i][0] == 'Iris-versicolor' :
        Y.append(1)
    elif y.iloc[i][0] == 'Iris-virginica' :
        Y.append(1)
Y = np.array(Y)
Y = Y.reshape(150,1)
sys.maxsize = None
q =inss.grad(Y,x,0.00000001)
print(q)
# print(Y)
# print(X.iloc[0][0])
# print(y.shape)
# print(iris.data.targets)

C:\Users\ahnb2\AppData\Local\Temp\ipykernel_24704\3096954510.py:63: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  x.append(X.iloc[i][j])
C:\Users\ahnb2\AppData\Local\Temp\ipykernel_24704\3096954510.py:69: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y.iloc[i][0] == 'Iris-setosa' :
C:\Users\ahnb2\AppData\Local\Temp\ipykernel_24704\3096954510.py:71: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y.iloc[i][0] == 'Iris-versicolo

mean(err) = 0.004999738113479282
895809
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
m = [1,2,3,4,5,6,7,8]
m = np.array(m)
m= m.reshape(2,4)
print(m)

[[1 2 3 4]
 [5 6 7 8]]
